### ISSUE TITLE
Unable to locate file

### ISSUE THREAD

**Issue by niczap** [socialigniter/socialigniter#44]
Hi,

after installing "Social Igniter" (last version) in local (WAMP environment), i have the following error in the browser:

An Error Was Encountered

Unable to locate the views/ file: {"theme":"site_default","name":"Default Site","created":"2011-04-14","updated":"2011-04-14","creator":"Brennan Novak","layouts":{"sidebar":["content","sidebar","wide"],"wide":["wide"],"profile":["content","sidebar"]}}/theme_schema.php

Moreover, in the debug file I have:

DEBUG - 2011-11-30 15:39:02 --> Config Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Hooks Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Utf8 Class Initialized
DEBUG - 2011-11-30 15:39:02 --> UTF-8 Support Enabled
DEBUG - 2011-11-30 15:39:02 --> URI Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Router Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the config/ file: routes.php
DEBUG - 2011-11-30 15:39:02 --> No URI present. Default controller set.
DEBUG - 2011-11-30 15:39:02 --> Output Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Security Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Input Class Initialized
DEBUG - 2011-11-30 15:39:02 --> XSS Filtering completed
DEBUG - 2011-11-30 15:39:02 --> XSS Filtering completed
DEBUG - 2011-11-30 15:39:02 --> Global POST and COOKIE data sanitized
DEBUG - 2011-11-30 15:39:02 --> Language Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Language Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Config Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Loader Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the config/ file: social_igniter.php
DEBUG - 2011-11-30 15:39:02 --> Config file loaded: application/config/social_igniter.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the config/ file: settings.php
DEBUG - 2011-11-30 15:39:02 --> Config file loaded: application/config/settings.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the config/ file: custom.php
DEBUG - 2011-11-30 15:39:02 --> Config file loaded: application/config/custom.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: url_helper.php
DEBUG - 2011-11-30 15:39:02 --> Helper loaded: url_helper
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: cookie_helper.php
DEBUG - 2011-11-30 15:39:02 --> Helper loaded: cookie_helper
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: date_helper.php
DEBUG - 2011-11-30 15:39:02 --> Helper loaded: date_helper
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: text_helper.php
DEBUG - 2011-11-30 15:39:02 --> Helper loaded: text_helper
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: feed_helper.php
DEBUG - 2011-11-30 15:39:02 --> Helper loaded: feed_helper
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: view_helper.php
DEBUG - 2011-11-30 15:39:02 --> Helper loaded: view_helper
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: array_helper.php
DEBUG - 2011-11-30 15:39:02 --> Helper loaded: array_helper
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: string_helper.php
DEBUG - 2011-11-30 15:39:02 --> Helper loaded: string_helper
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: directory_helper.php
DEBUG - 2011-11-30 15:39:02 --> Helper loaded: directory_helper
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: social_igniter_helper.php
DEBUG - 2011-11-30 15:39:02 --> Helper loaded: social_igniter_helper
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: custom_helper.php
DEBUG - 2011-11-30 15:39:02 --> Helper loaded: custom_helper
DEBUG - 2011-11-30 15:39:02 --> Database Driver Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the libraries/ file: session.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the config/ file: session.php
DEBUG - 2011-11-30 15:39:02 --> Session Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: string_helper.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the libraries/ file: encrypt.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the config/ file: encrypt.php
DEBUG - 2011-11-30 15:39:02 --> Encrypt Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Session routines successfully run
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the libraries/ file: form_validation.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the config/ file: form_validation.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the helpers/ file: form_helper.php
DEBUG - 2011-11-30 15:39:02 --> Helper loaded: form_helper
DEBUG - 2011-11-30 15:39:02 --> Form Validation Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the libraries/ file: social_auth.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the config/ file: social_auth.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: auth_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: connections_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the libraries/ file: social_igniter.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the config/ file: social_igniter.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the config/ file: activity_stream.php
DEBUG - 2011-11-30 15:39:02 --> Config file loaded: application/config/activity_stream.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: activity_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: content_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: pages_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: settings_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: sites_model.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the libraries/ file: social_tools.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the config/ file: social_tools.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: categories_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: comments_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: places_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: ratings_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: relationships_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: tags_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: taxonomy_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the models/ file: upload_model.php
DEBUG - 2011-11-30 15:39:02 --> Model Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Controller Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Site MX_Controller Initialized
DEBUG - 2011-11-30 15:39:02 --> Loader Class Initialized
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the language/english/ file: social_igniter_lang.php
DEBUG - 2011-11-30 15:39:02 --> Language file loaded: language/english/social_igniter_lang.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the language/english/ file: activity_stream_lang.php
DEBUG - 2011-11-30 15:39:02 --> Language file loaded: language/english/activity_stream_lang.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the libraries/ file: user_agent.php
DEBUG - 2011-11-30 15:39:02 --> Unable to locate the config/ file: user_agent.php
DEBUG - 2011-11-30 15:39:02 --> User Agent Class Initialized

Could you help me?

Tnx
NicZap

**Comment by socialigniter** [comment]
Hi There, 

Sorry about the bug. I think it is fixed. Do a fresh pull or download of the repository. 

If it is still giving you an error hit me up one of the following chat methods as it may be a *nix / Windows issue that I haven't experienced yet.

Skype: astropix
AIM: flyingbrennan
Google: reverseproductions
IRC Freenode: brennannovak

Cheers, BN

**Comment by niczap** [comment]
Thanks, but I have the same problem with new version too :-(

I use PHP version 5.3.4, apache 2.2.17 and MySql 5.1.53 on Windows 7 X64 ... seems an errore relative to JSON decode!

See you soon
Nz

**Comment by socialigniter** [comment]
Totally sorry about that! You are correct... I forgot to update the application/install/DATABASE.sql

In order to fix that you can either:

Pull the most recent repo and wipe your database and reinstall it with the above file.

Or run this SQL command in your database:

UPDATE settings SET value='site_default' WHERE setting='site_theme';
UPDATE settings SET value='mobile_default' WHERE setting='mobile_theme';

I used t store JSON theme config in the database... was a bad idea... now I store it in a php file that gets loaded. That is what was causing the error!

**Comment by niczap** [comment]
Besides "site_theme" I had to update also the value of the "url" field in the db. Infact my base_url is not "localhost" but "localhost/social". Now, if I would signup, the application has the error that not found "http://localhost/api/users/signup". Probably because not parse correctly the base_url that is "localhost/social".

Tnx
NicZap
