### ISSUE TITLE
Twitter timeline 404

### ISSUE THREAD

**Issue by sebilasse** [socialigniter/socialigniter#47]
Hey there,

connected twitter (http://social-igniter.com).
Clicked link for /home/twitter/timeline
Get Error "Unable to locate the views/ file: dashboard_default/partials/status_updater.php"

**Comment by bnvk** [comment]
Hey Sebastian. Thanks for filing this. I have fixed the bug now.

In the future please file bugs with the repo where the specific app has the bug you are experiencing- e.g. you would have filed this at https://github.com/socialigniter/twitter
