### ISSUE TITLE
Add error handling to stages of Installer.php

### ISSUE THREAD

**Issue by bnvk** [socialigniter/socialigniter#52]
Currently the installer seems to fail on numerous steps for different people. Issues could be anywhere from DB creds failing, to not having the DB already created (see other issue), to file write permissions. The fact is that we need the installer to check all these conditions and return UI feedback to the user. 

Also, it should allow a person to continue installing from previously completed steps. Currently this is not possible!

**Comment by barnabywalters** [comment]
Fixed lack of error reporting at the first stages, so I'm closing this issue and opening a separate one for picking up where the previous install attempt left off.
