### ISSUE TITLE
Too many user session cookies are sent on login

### ISSUE THREAD

**Issue by aaronpk** [socialigniter/socialigniter#57]
When logging in, the system is sending multiple set-cookie headers with new user session data in each one. On the login request I got 16 set-cookie headers. 

When running in nginx using php-fpm, nginx refuses to send the response because the headers are too big. The error message in the nginx log is "upstream sent too big header while reading response header from upstream".

**Comment by bnvk** [comment]
Fixed this with commit: 6fd03bdd97d6c192384a8f596812272c67aaf73b
