### ISSUE TITLE
File permissions issues during install

### ISSUE THREAD

**Issue by laymonk** [socialigniter/socialigniter#68]
Hi,

I have just tried to install socialigniter, but the installer is getting stuck claiming it has no permissions to write to the files .. I have tried chmod'ing to 666 and then 777 the files (and even the directory), but I can't get past the error.

I peered in the install.php, and where is_writable is called needed to be negated, so it can go past the not writable error message .. But still the installer fails to proceed .. 

Looking at the logs, i see:
<code>

2013/12/07 06:37:35 [error] 19626#0: *25 open() "/www/igniter/setup" failed (2: No such file or directory), client: 192.168.10.99, server: 192.168.10.20, request: "POST /setup HTTP/1.1", host: "192.168.10.20", referrer: "https://192.168.10.20/install.php"

</code>

Looking at the directory tree, the only executable file named like setup are:
- ./application/controllers/setup.php
- ./js/installer/setup.js

So, it seems as if the install script is possibly making a wrong assumption about the path of that file, or is assuming some alias settings within the web server.

Please, can anyone throw more light on this .. Perhaps I am missing something.

PS:  This looks like some great work .. I am honoured to have access to try and get it to work .. Well done.

**Comment by laymonk** [comment]
Forgot to say:  This s running off nginx/php-fpm

**Comment by laymonk** [comment]
OK, it seems line 53 of js/installer/setup.js .. may be the cause of this.
53             url      : $('#base_url').val() + 'setup',

Would probably be quicker for someone more familiar with the system to give me some leads or pointers ..

**Comment by laymonk** [comment]
It really seems to be an issue with the step-2 code block on setup.js .. 

```
      $('#step_2').fadeIn();
      $.ajax({
        url      : $('#base_url').val() + 'setup',
        type     : 'POST',
        dataType : 'json',
        data     : data,
        success  : function(result) {
          console.log('Step 2');
          console.log(result);
          $('#step_2').fadeOut();
          $('#step_3').fadeIn();
        }
```

There is no top level dir named setup, and I am not sure exactly what this step 2 is trying to accomplish ..

**Comment by laymonk** [comment]
Seems this project is abandoned .. pity.  Looked promising, and seems to have a sound foundation. I would really have wanted to have tried to contribute.  But what is this with indieweb oriented projects ending up being just a talking point for the guy who originally authored it before abandoning it ?  Often, the project focus just does not match the lofty posts about indieweb projects  ..  Puzzling ..

**Comment by socialigniter** [comment]
Hi @chuze apologies for not getting back to you sooner. You're partially right- the project is not "abandoned" but it is on my back burner for sure, and no one else has picked up the torch and stepped in with carrying on development. I've moved onto the Mailpile project for my day to day work, but I still use Social-igniter for my personal site as well as another personal project. Currently it is a tad bit behind implementing all IndieWeb protocols, this is simply due to a lack of development time, I add little bit here and there as I go.

The bug you're experiencing I believe stems from nginx stack, which SI has not been tested nearly enough on. I'm happy to help you debug & get an instance up and running if you're interested in contributing! The best way is on IRC freenode, my handle is _bnvk_

**Comment by laymonk** [comment]
I am really grateful to receive your reply, and thanks for the insight and explanation.  

Yes, I am quite keen at trying to get this platform working .. Given your hint of a potential issue with nginx, I will quickly test it on apache, and then choose whether to try and get it working on nginx as well or to have nginx proxy-off to apache just for SI.  

I have recently become a fan of static blog systems like peilcan, but the indieweb ideas and features make SI a compelling alternative to give a serious look at.  I am surprised that many more folks are not interested in SI.  My peek at indieweb tools revealed SI and storytlr as great tools to consider using and extending. 

Will certainly look you up on IRC .. best regards.

**Comment by laymonk** [comment]
Finally, had a chance to look at this .. on apache in a VM.

Initially tried to set it up via a sub-directory (ie, not /) .. and had a wild ride trying to sort out so many path access oriented issues .. hacked around the various files that had hard-coded access and never relied on .htaccess 'RewriteBase'  (even the css files) .. In the end, I had to conclude that some form of URI routing logic needs to be added in before it SI can be deployed in a directory.  But the experience of trying to get it to work was helpful, and showed me glimpses of the system ..

So, I created a new VHost, but still got issues .. from my previous tinkering with various files.  So, did a fresh git clone, and this time left everything as is .. and it installed and is running fine.  I have actually now installed a few apps, by git cloning and using the admin GUI to install them.  Some are failing, but that is no issue ..

Man, this thing is smooth and well thought out, and I am keen to have a good play with it.  Just started forking it.  The last time I coded in PHP was too long ago when no frameworks existed, and I have never used a php framework before .. I researched a bit about codeigniter and it seems reasonably easy to get into.  Yes, there are issues around using it longer term, (ie EllisLabs support, etc) but it seems like an easy system to quickly get into .. So, I am sold on this.  

Will start by running a personal blog on it, and then try to introduce some things I am keen on (like creating blogs, notes, etc) via markdown/restructured text .. and perhaps even creating new content on the CLI using markdown and restructured text .. Yeah, why not get social blogging while enjoying the usefulness of static site generators (if that is possible) .. 

Well done, you have some wicked foundation here .. I am really amazed that there is little interest in the community around this system.  

Will be in touch to seek your guidance on how best to contribute stuff .. docs, code, etc ..

**Comment by bnvk** [comment]
@chuze cool, i'm glad you were able to get it up and running- and that you like what I am doing :)

Yah, I think some of the reason "the community" didn't get as involved as I had hoped was firstly due to PHP, then as Aaron PK and Barnaby and many others ended up rolling their solutions in PHP, the other reason was due to CodeIgniter as EllisLabs has continued to make silly decisions- I'd love to eventually migrate SI into more framework independent Composer modules... but time... resources... I'm pretty tied up with Mailpile at present. 

Anywho, send me emails rather than keeping this thread open https://brennannovak.com/#!/contact

Also, please feel free to send over a pull request with your updates :)

**Comment by laymonk** [comment]
Thanks again for replying, Brennan .. And mailpile does look truly awesome as a project .. This from someone who pays for postbox as a mailclient (even via wine on linux) .. so, keep up the great works, and I do hope that project succeeds.

Regarding framework independence, codeigniter is alive and kicking it seems (with or without EllisLabs) ..  I was thinking more like putting an extra layer like CI-bonfire between codeigniter and SI, so SI can focus more on application features and less on backend admin .. As to codeigniter putting off others, I doubt that very much because codeigniter is a really fast system to pick up .. so, much so that even myself have picked it up reasonably well within a few days of poking about .. 

Will close this issue now .. and try and reach you via other ways in future .. thanks again for the response
